### ISSUE TITLE
安装依赖库报错

### ISSUE THREAD

**Issue by Lunction** [dqzg12300/kAlgorithmTools#1]
File "C:\Users\Lunction\Desktop\kAlgorithmTools\kwindow\kmainForm.py", line 7, in <module>
    from common import Util, AsmUtil, Enums, CryptoUtil
ImportError: cannot import name 'Util' from 'common' (C:\Users\Lunction\AppData\Local\Programs\Python\Python39\lib\site-packages\common\__init__.py)

**Comment by dqzg12300** [comment]
修改下目录下面common的目录名称。重新引用下即可。这是因为你有个库是common。然后和目录重名导致的。

**Comment by Lunction** [comment]
我修改了 还是提示这个找不到

**Comment by Lunction** [comment]
包括安装依赖库的指定版本都过期了

**Comment by dqzg12300** [comment]
我修改目录名重新提交了。是说pyqt5的依赖版本低是我自己环境安装后一直没升。这个应该没啥影响的。你直接用最新版本的就行

**Comment by Lunction** [comment]
我删除了文件 支持库都放在当前目录下面 des算法没有执行

**Comment by dqzg12300** [comment]
查了下。这个功能当时界面搞好，没实现。你拉下最新代码。我做完提交了
